name: FedModule
channels:
  - defaults
dependencies:
  - pip
  - python=3.8
  - pip:
    - numpy==1.24.1
    - pandas==1.4.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - torch==2.3.0
    - torchaudio==2.3.0
    - torchvision==0.18.0
    - wandb==0.17.0
    - kmeans1d==0.3.1
    - paho-mqtt==2.1.0
